import Head from 'next/head'
import Button from '../components/Button'

export default function Home() {
  return (
    <div className='w-full min-h-screen bg-space-cadet'>
      <Head>
        <title>PseudoRep</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex items-center justify-between p-10'>
        <h1 className='text-cotton-candy text-4xl font-dosis font-bold'>Pseudo <span className='font-rubik text-dogwood-rose '>Rep</span></h1>
        <Button onClick={() => console.log('LOL')}>Connect Wallet</Button>
      </div>
      <div className='flex flex-col items-center justify-center w-full gap-4'>
        <h1 className='text-6xl font-bold text-eggshell tracking-widest mt-40'>Know your ReputeX</h1>
        <p className='text-lg font-medium text-cotton-candy tracking-wider'>Unlock a new dimension with your Web3 credit score</p>
        <div className='w-[30rem] rounded-full bg-eggshell mt-12 flex items-center justify-between p-2'>
          <input className='w-2/3 h-10 bg-transparent rounded-full p-2 placeholder:text-blue-violet placeholder:text-opacity-50 text-blue-violet outline-none' placeholder='0xDAF....8Bc5 or ENS or UD'/>
          <Button>{`Let's go`}</Button>
        </div>
      </div>
    </div>
  )
}
