import Head from 'next/head'
import Button from '../components/Button'
import About from '../components/About'
import Features from '../components/Features'
import { motion } from 'framer-motion'
import { useRouter } from 'next/router'

const backgroundVariants = {
  visible: {
    rotateX: [0,90,180,0],
    rotateY: [0,90,180,0],
    scale: [1,0.5,0.2,1],
    backgroundColor: ["#D90368","#FFB2E6","#2E294E"],
    transition: {
      delay: 0.5,
      duration: 4,
      type: 'spring',
      stiffness: 50,
      repeat: Infinity,
    }
  }
}

const backgroundVariants2 = {
  visible: {
    rotateX: [0,90,180,0],
    rotateY: [0,90,180,0],
    scale: [0.8,0.2,0.5,0.8],
    backgroundColor: ["#FFB2E6","#2E294E","#D90368",],
    transition: {
      delay: 0.5,
      duration: 7,
      repeat: Infinity,
      repeatType: "mirror"
    }
  }
}


export default function Home() {
  const router = useRouter()
  return (
    <div className='w-full min-h-screen bg-space-cadet'>
      <Head>
        <title>PseudoRep</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div className="absolute w-20 h-20 rounded-3xl left-0 bottom-40" variants={backgroundVariants} animate="visible"></motion.div>
      <motion.div className="absolute w-20 h-20 rounded-3xl right-10 top-40" variants={backgroundVariants} animate="visible"></motion.div>
      <motion.div className="absolute w-40 h-40 rounded-tr-3xl rounded-bl-3xl right-14 top-80" variants={backgroundVariants2} animate="visible"></motion.div>
      <motion.div className="absolute w-40 h-40 rounded-tr-3xl rounded-bl-3xl left-14 top-40" variants={backgroundVariants2} animate="visible"></motion.div>
      <div className='flex flex-col items-center justify-center w-full gap-4 py-40'>
        <h1 className='text-6xl font-bold text-eggshell tracking-widest'>Know your Score</h1>
        <p className='text-lg font-medium text-cotton-candy tracking-wider'>Unlock a new dimension with your Web3 credit score</p>
        <div className='w-[30rem] rounded-full bg-eggshell mt-12 flex items-center justify-between p-2'>
          <input className='w-2/3 h-10 bg-transparent rounded-full p-2 placeholder:text-blue-violet placeholder:text-opacity-50 text-blue-violet outline-none' placeholder='0xDAF....8Bc5 or ENS or UD'/>
          <Button onClick={() => router.push('/chainbreakdown')}>{`Let's go`}</Button>
        </div>
      </div>
      <About />
      <Features />
    </div>
  )
}
